name: Run tests
on: [push, pull_request]

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16, 18, 19]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 3

    - name: Set Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install npm dependencies
      run: npm ci

    - name: Run tests
      run: npm test
